title:             Tomas Tabak
email:             tomastabak@gmail.com
description:       This is it
author:            Tomas Tabak
baseurl:           "/startbootstrap-clean-blog-jekyll"
url:               "http://github.TomasTabak/startbootstrap-clean-blog-jekyll"

# Social Profiles
twitter_username:  SBootstrap
github_username:   BlackrockDigital
facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
