title:             Tomas Tabak
email:             tomastabak@gmail.com
description:       Thoughts of an aspiring individual
author:            Tomas Tabak
baseurl:           "/startbootstrap-clean-blog-jekyll"
url:               "http://github.TomasTabak/startbootstrap-clean-blog-jekyll"

# Social Profiles
twitter_username:  tomastabakk
github_username:   tomastabak
facebook_username: tomastabak
instagram_username: tomastabak

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
